#!/usr/bin/env bash
#
# Plexus self-host installer.
#
#   curl -fsSL https://plexus.company/install.sh | bash
#
# One repo, a few questions, every secret generated locally, the whole
# platform up with docker compose. Prefers prebuilt images from ghcr.io
# (pinned by PLEXUS_VERSION); falls back to building from source if images
# aren't available. Nothing phones home — license validation included.
#
# Also usable from a checkout:  ./selfhost/install.sh [install|upgrade|doctor]
set -euo pipefail

REPO="${PLEXUS_REPO:-https://github.com/plexus-oss/plexus.git}"
VERSION="${PLEXUS_VERSION:-latest}"
BOLD=$(tput bold 2>/dev/null || true); DIM=$(tput dim 2>/dev/null || true); RESET=$(tput sgr0 2>/dev/null || true)

say()  { printf '%s\n' "${1-}"; }
ask()  { local q="$1" d="${2-}"
  if [ -n "$d" ]; then printf '%s %s[%s]%s ' "$q" "$DIM" "$d" "$RESET"; else printf '%s ' "$q"; fi
  read -r REPLY </dev/tty || REPLY=""
  REPLY="${REPLY:-$d}"
}
gen() { openssl rand -hex "${1:-32}"; }
sha256() { if command -v sha256sum >/dev/null 2>&1; then sha256sum | cut -d' ' -f1; else shasum -a 256 | cut -d' ' -f1; fi }

compose() { docker compose -f "$SELFHOST_DIR/docker-compose.yml" --env-file "$SELFHOST_DIR/.env" "$@"; }

# ---- figure out where we are ---------------------------------------------
# Running from a checkout? (script lives in <repo>/selfhost/)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-.}")" 2>/dev/null && pwd || pwd)"
if [ -f "$SCRIPT_DIR/docker-compose.yml" ] && [ -d "$SCRIPT_DIR/../gateway" ]; then
  SELFHOST_DIR="$SCRIPT_DIR"
else
  SELFHOST_DIR="" # piped via curl — we'll clone below
fi

CMD="${1:-install}"

# ---- doctor / upgrade (checkout mode) ------------------------------------
if [ "$CMD" = "doctor" ] && [ -n "$SELFHOST_DIR" ]; then
  compose ps
  say ""
  say "App health:     curl -fsS http://localhost:3000/api/ping"
  say "Gateway health: curl -fsS http://localhost:8080/health"
  exit 0
fi
if [ "$CMD" = "upgrade" ] && [ -n "$SELFHOST_DIR" ]; then
  say "… pulling $VERSION images and restarting"
  git -C "$SELFHOST_DIR/.." pull --ff-only || true
  compose pull --ignore-buildable || true
  compose up -d --remove-orphans
  exit 0
fi

say ""
say "${BOLD}Plexus self-host installer${RESET}"
say "The full platform — ingest, storage, dashboards, alerts — on your own hardware."
say ""

# ---- preflight ------------------------------------------------------------
for cmd in git docker openssl; do
  command -v "$cmd" >/dev/null 2>&1 || { say "✗ $cmd is required but not installed."; exit 1; }
done
docker compose version >/dev/null 2>&1 || { say "✗ docker compose v2 is required."; exit 1; }
docker info >/dev/null 2>&1 || { say "✗ docker daemon isn't running."; exit 1; }

# ---- questions ------------------------------------------------------------
if [ -z "$SELFHOST_DIR" ]; then
  ask "Install directory?" "./plexus"
  INSTALL_DIR="$REPLY"
fi

ask "Hostname browsers will use (bare host, no scheme)?" "localhost"
HOST="$REPLY"

ask "Anthropic API key for the Terminal AI copilot (Enter to skip)?" ""
ANTHROPIC_KEY="$REPLY"

ask "Resend API key for sign-in code emails (Enter to skip — codes will appear in 'docker compose logs frontend')?" ""
RESEND_KEY="$REPLY"

# ---- clone (curl mode) ----------------------------------------------------
if [ -z "$SELFHOST_DIR" ]; then
  if [ -d "$INSTALL_DIR/.git" ]; then
    say "✓ repo already cloned at $INSTALL_DIR"
  else
    say "… cloning plexus"
    git clone --depth 1 "$REPO" "$INSTALL_DIR"
  fi
  SELFHOST_DIR="$(cd "$INSTALL_DIR/selfhost" && pwd)"
fi

# ---- secrets --------------------------------------------------------------
ENV_FILE="$SELFHOST_DIR/.env"
if [ -f "$ENV_FILE" ]; then
  say "✓ .env exists — keeping your existing secrets (delete it to regenerate)"
else
  say "… generating secrets (stored only in selfhost/.env)"
  CH_WRITER_PW=$(gen 16); CH_READER_PW=$(gen 16); CH_ADMIN_PW=$(gen 16)
  cat > "$ENV_FILE" <<EOF
# Generated by install.sh $(date -u +%Y-%m-%dT%H:%M:%SZ) — all values local to this install.
PLEXUS_VERSION=$VERSION
PLEXUS_APP_URL=http://$HOST:3000
PLEXUS_GATEWAY_PUBLIC_HOST=$HOST:8080
GATEWAY_ALLOWED_ORIGINS=$HOST:*

POSTGRES_PASSWORD=$(gen 16)
AUTH_SECRET=$(gen 32)
PLEXUS_INTERNAL_SECRET=$(gen 32)
ENCRYPTION_KEYS=v1:$(gen 32)

CH_REPLICATION_SECRET=$(gen 16)
CH_WRITER_PASSWORD=$CH_WRITER_PW
CH_READER_PASSWORD=$CH_READER_PW
CH_ADMIN_PASSWORD=$CH_ADMIN_PW
CH_WRITER_PASSWORD_SHA256=$(printf %s "$CH_WRITER_PW" | sha256)
CH_READER_PASSWORD_SHA256=$(printf %s "$CH_READER_PW" | sha256)
CH_ADMIN_PASSWORD_SHA256=$(printf %s "$CH_ADMIN_PW" | sha256)

MINIO_ROOT_USER=plexus
MINIO_ROOT_PASSWORD=$(gen 16)

# Optional — fill in later and re-run: ./selfhost/install.sh upgrade
ANTHROPIC_API_KEY=$ANTHROPIC_KEY
RESEND_API_KEY=$RESEND_KEY
RESEND_FROM_ADDRESS=
# Enterprise license key (leave blank for the free tier).
PLEXUS_LICENSE=
EOF
  chmod 600 "$ENV_FILE"
fi

# ---- up -------------------------------------------------------------------
say ""
if compose pull --ignore-buildable 2>/dev/null; then
  say "… starting with prebuilt images ($VERSION)"
  compose up -d --no-build
else
  say "… prebuilt images unavailable — building from source (first build takes a few minutes)"
  compose up -d --build
fi

say ""
say "${BOLD}Plexus is starting.${RESET}"
say ""
say "  App:      http://$HOST:3000"
say "  Ingest:   ws://$HOST:8080  (gateway)"
say "  Read API: http://$HOST:8000"
say ""
if [ -z "$RESEND_KEY" ]; then
  say "  Sign in with any email address — the 6-digit code appears in:"
  say "    docker compose -f $SELFHOST_DIR/docker-compose.yml logs -f frontend"
  say ""
fi
say "  Status:   ./selfhost/install.sh doctor"
say "  Upgrade:  ./selfhost/install.sh upgrade"
say "  Stop:     docker compose -f $SELFHOST_DIR/docker-compose.yml down"
say ""
say "Everything here is free for a single team — no caps, no phone-home."
say "Enterprise features (SSO, RBAC, audit logs, multi-tenancy) unlock with a"
say "license key in selfhost/.env → PLEXUS_LICENSE. See docs/licensing.md."
