#!/usr/bin/env bash
#
# Generate the local-dev env for the one-click backend stack. Idempotent:
#   - local/.env  (backend secrets/passwords) — created once, then reused so
#     restarts keep working against the existing ClickHouse/MinIO volumes.
#   - ../.env.development.local  (Next's highest-precedence dev file) —
#     regenerated each run to point the host-run frontend at the local Docker
#     backend. We OWN this file; your .env.local is never touched. Delete it to
#     revert the frontend to whatever .env.local points at.
#
# The one thing that must match on both sides is PLEXUS_INTERNAL_SECRET (internal
# service auth). We seed it from ../.env.local if present, else generate.
set -euo pipefail

LOCAL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"   # frontend/local
FE_ROOT="$(cd "$LOCAL_DIR/.." && pwd)"                       # frontend
ENV_FILE="$LOCAL_DIR/.env"
FE_LOCAL="$FE_ROOT/.env.local"
FE_DEV_LOCAL="$FE_ROOT/.env.development.local"

command -v openssl >/dev/null || { echo "✗ openssl required" >&2; exit 1; }
gen() { openssl rand -hex "${1:-16}"; }

# sha256 of a plaintext (users.xml resolves password hashes via from_env=).
sha256() {
  if command -v shasum >/dev/null; then printf %s "$1" | shasum -a 256 | cut -d' ' -f1
  else printf %s "$1" | sha256sum | cut -d' ' -f1; fi
}

# Read KEY= from an env file (last wins, strips surrounding quotes). Empty if absent.
read_env() {
  local key="$1" file="$2" line
  [ -f "$file" ] || return 0
  line="$(grep -E "^${key}=" "$file" | tail -n1)" || return 0
  line="${line#*=}"; line="${line%\"}"; line="${line#\"}"; line="${line%\'}"; line="${line#\'}"
  printf '%s' "$line"
}

# ── local/.env (backend) — create once, reuse thereafter ─────────────────────
if [ -f "$ENV_FILE" ]; then
  echo "▸ reusing existing $ENV_FILE"
  # shellcheck disable=SC1090
  set -a; . "$ENV_FILE"; set +a
  # Migration: older generated files predate the per-user ClickHouse passwords
  # (writer/reader/admin + *_SHA256 hashes for users.xml from_env=). Backfill
  # any that are missing so a stale .env keeps working after the compose bump.
  MIGRATED=0
  if [ -z "${CH_WRITER_PASSWORD:-}" ]; then CH_WRITER_PASSWORD="${CH_PLEXUS_PASSWORD:-$(gen 16)}"; MIGRATED=1; fi
  if [ -z "${CH_READER_PASSWORD:-}" ]; then CH_READER_PASSWORD="$(gen 16)"; MIGRATED=1; fi
  if [ -z "${CH_ADMIN_PASSWORD:-}" ];  then CH_ADMIN_PASSWORD="$(gen 16)";  MIGRATED=1; fi
  if [ -z "${CH_REPLICATION_SECRET:-}" ]; then CH_REPLICATION_SECRET="$(gen 16)"; MIGRATED=1; fi
  if [ "$MIGRATED" = 1 ] || [ -z "${CH_WRITER_PASSWORD_SHA256:-}" ]; then
    echo "▸ backfilling new ClickHouse vars into $ENV_FILE"
    CH_WRITER_PASSWORD_SHA256="$(sha256 "$CH_WRITER_PASSWORD")"
    CH_READER_PASSWORD_SHA256="$(sha256 "$CH_READER_PASSWORD")"
    CH_ADMIN_PASSWORD_SHA256="$(sha256 "$CH_ADMIN_PASSWORD")"
    {
      echo "# Backfilled by dev-setup.sh (per-user ClickHouse creds + users.xml hashes)"
      echo "CH_WRITER_PASSWORD=$CH_WRITER_PASSWORD"
      echo "CH_READER_PASSWORD=$CH_READER_PASSWORD"
      echo "CH_ADMIN_PASSWORD=$CH_ADMIN_PASSWORD"
      echo "CH_REPLICATION_SECRET=$CH_REPLICATION_SECRET"
      echo "CH_WRITER_PASSWORD_SHA256=$CH_WRITER_PASSWORD_SHA256"
      echo "CH_READER_PASSWORD_SHA256=$CH_READER_PASSWORD_SHA256"
      echo "CH_ADMIN_PASSWORD_SHA256=$CH_ADMIN_PASSWORD_SHA256"
    } >> "$ENV_FILE"
    export CH_WRITER_PASSWORD CH_READER_PASSWORD CH_ADMIN_PASSWORD \
      CH_REPLICATION_SECRET CH_WRITER_PASSWORD_SHA256 \
      CH_READER_PASSWORD_SHA256 CH_ADMIN_PASSWORD_SHA256
  fi
else
  echo "▸ generating $ENV_FILE (one-time backend secrets)"
  PLEXUS_INTERNAL_SECRET="$(read_env PLEXUS_INTERNAL_SECRET "$FE_LOCAL")"
  [ -n "$PLEXUS_INTERNAL_SECRET" ] || PLEXUS_INTERNAL_SECRET="$(gen 32)"
  # Per-user ClickHouse plaintexts, mirroring prod's users.xml
  # (telemetry_writer / nextjs_reader / admin). users.xml consumes the
  # *_SHA256 hashes via from_env=; the services get the plaintexts.
  CH_WRITER_PASSWORD="$(gen 16)"
  CH_READER_PASSWORD="$(gen 16)"
  CH_ADMIN_PASSWORD="$(gen 16)"
  CH_REPLICATION_SECRET="$(gen 16)"
  MINIO_ROOT_USER="plexus"
  MINIO_ROOT_PASSWORD="$(gen 16)"
  cat > "$ENV_FILE" <<EOF
# GENERATED by local/dev-setup.sh — local backend secrets. Safe to delete to
# reset (also wipe volumes: make clean). Not committed (.gitignore: .env*).
PLEXUS_INTERNAL_SECRET=$PLEXUS_INTERNAL_SECRET
CH_WRITER_PASSWORD=$CH_WRITER_PASSWORD
CH_READER_PASSWORD=$CH_READER_PASSWORD
CH_ADMIN_PASSWORD=$CH_ADMIN_PASSWORD
CH_REPLICATION_SECRET=$CH_REPLICATION_SECRET
CH_WRITER_PASSWORD_SHA256=$(sha256 "$CH_WRITER_PASSWORD")
CH_READER_PASSWORD_SHA256=$(sha256 "$CH_READER_PASSWORD")
CH_ADMIN_PASSWORD_SHA256=$(sha256 "$CH_ADMIN_PASSWORD")
MINIO_ROOT_USER=$MINIO_ROOT_USER
MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
EOF
  set -a; . "$ENV_FILE"; set +a
fi

# ── ../.env.development.local — point the host frontend at local Docker ───────
echo "▸ writing $FE_DEV_LOCAL (frontend → local Docker backend)"
cat > "$FE_DEV_LOCAL" <<EOF
# GENERATED by \`make dev\` (local/) — overrides that point this frontend at the
# local Dockerized backend (local/docker-compose.dev.yml). Higher precedence
# than .env.local in Next dev. DELETE THIS FILE to revert to your .env.local.
PLEXUS_CLICKHOUSE_URL=http://localhost:8123
PLEXUS_CLICKHOUSE_USER=nextjs_reader
PLEXUS_CLICKHOUSE_PASSWORD=$CH_READER_PASSWORD
PLEXUS_CLICKHOUSE_DATABASE=plexus
PLEXUS_CLICKHOUSE_WRITER_USER=telemetry_writer
PLEXUS_CLICKHOUSE_WRITER_PASSWORD=$CH_WRITER_PASSWORD
PLEXUS_GATEWAY_URL=http://localhost:8080
PLEXUS_ALERT_SERVICE_URL=http://localhost:8081
PLEXUS_LOADER_URL=http://localhost:8082
NEXT_PUBLIC_GATEWAY_HOST=localhost:8080
PLEXUS_INTERNAL_SECRET=$PLEXUS_INTERNAL_SECRET
EOF

echo "✓ env ready"
